spring:
  cloud:
    gateway:
      routes:
        #        - id: main-service
        #          uri: lb://MAIN-SERVICE
        #          predicates:
        #            - Path=/main-service/**

        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/main-service/**
          #            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
#            - AuthorizationHeaderFilter
            - AuthFilter
            - RemoveRequestHeader=Cookie
        
        #         Spring Cloud config with actuator
        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/main-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
